version: '3.8'
services:
  localstack:
    container_name: localstack-aws
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
